import { planStops, morphWindow } from './engine.js';
import { buildPathD } from './path.js';

// jsDelivr mirrors npm, so the bonus plugins are guaranteed to be present.
const GSAP_CDN = 'https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist';

const j = (v) => JSON.stringify(v);
const n = (v) => Math.round(v * 1000) / 1000;
const oneLine = (s) => String(s ?? '').replace(/[\r\n]+/g, ' ');

/**
 * Resolve against the assets that were PASSED IN, never a global store — the
 * exporter has to be able to emit a scene it is not currently editing.
 */
const assetFrom = (assets, id) => assets.find((a) => a.id === id) ?? assets[0] ?? null;

/**
 * Emits the timeline UNROLLED — one explicit call per keyframe rather than a
 * loop over exported data. It is longer, but it is the form you can actually
 * read, diff and hand-edit afterwards, which is the whole point of authoring
 * here instead of writing the GSAP by hand.
 */
export function buildTimelineJs({ project, scene, layout, track }) {
	const assets = project.assets;
	const s = track.settings;
	const { stops, duration } = planStops(track);
	const startAsset = assetFrom(assets, track.startingAssetId);
	const lines = [];
	const push = (line = '') => lines.push(line);

	// A newline in the name would break out of the line comment into live code.
	push(`// ${oneLine(project.name)} — ${oneLine(scene.name)} / ${oneLine(layout.name)}`);
	push(`// generated by webmotion-studio · total ${n(duration)}s`);
	push(`gsap.registerPlugin(MotionPathPlugin, MorphSVGPlugin);`);
	push();
	push(`const root  = document.querySelector('[data-gasp]');`);
	push(`const path  = root.querySelector('.gasp-path');`);
	push(`const place = root.querySelector('.gasp-place');`);
	push(`const life  = root.querySelector('.gasp-life');`);
	push(`const fx    = root.querySelector('.gasp-fx');`);
	push(`const size  = root.querySelector('.gasp-size');`);
	push(`const orient = root.querySelector('.gasp-orient');`);
	push(`const norm  = root.querySelector('.gasp-norm');`);
	push(`const shape = root.querySelector('.gasp-shape');`);
	push();
	push(`// A paused tween that maps 0..1 onto a position along the path.`);
	push(`const place1 = gsap.to(place, {`);
	push(`  duration: 1, ease: 'none', paused: true,`);
	push(`  motionPath: {`);
	push(`    path, align: path, alignOrigin: [0.5, 0.5],`);
	push(`    autoRotate: ${s.autoRotate ? s.rotationOffset || true : false}`);
	push(`  }`);
	push(`});`);
	push(`place1.progress(0.001); place1.progress(0); // force the first render`);
	push();
	push(`const at = { p: 0 };`);
	push(`const tl = gsap.timeline({`);
	push(`  repeat: ${scene.loop ? -1 : 0},`);
	push(`  yoyo: ${Boolean(scene.loop && scene.yoyo)},`);
	push(`  onUpdate() { place1.progress(at.p); }`);
	push(`});`);
	push();
	push(`// svgOrigin pins the artwork pivot to the origin; the default is the`);
	push(`// bounding-box centre, which moves as the shape morphs.`);
	push(`gsap.set(orient, { ...${j(startAsset.orient)}, svgOrigin: '0 0' });`);
	push();
	push(`tl.set(shape, { attr: { d: ${j(startAsset.d)} } }, 0)`);
	push(`  .set(norm, ${j(startAsset.norm)}, 0)`);
	push(`  .set(orient, ${j(startAsset.orient)}, 0)`);
	push(`  .set(size, { scale: ${n(s.objectSize / 100)} }, 0);`);
	push();

	let shape = startAsset;

	stops.forEach((stop, i) => {
		const next = stops[i + 1];
		const target = next ? next.state : stop.state;
		const label = stop.isStart ? 'start' : `marker ${i}`;

		push(
			`// ---- ${label}: arrive ${n(stop.arriveAt)}s @ path ${n(stop.from)}` +
				(stop.hold ? `, hold ${n(stop.hold)}s` : '') +
				` -> path ${n(stop.to)} over ${n(stop.travel)}s`
		);

		push(`tl.set(fx, { attr: { class: ${j(`gasp-fx ${stop.classes}`.trim())} } }, ${n(stop.arriveAt)})`);
		push(`  .set(fx, ${j(pickTransform(stop.state))}, ${n(stop.arriveAt)})`);
		push(`  .set(shape, ${j(pickPaint(stop.state))}, ${n(stop.arriveAt)})`);
		push(`  .set(at, { p: ${n(stop.from)} }, ${n(stop.arriveAt)});`);

		const win = morphWindow(stop);
		const targetAsset = win ? assetFrom(assets, stop.morphTarget) : null;
		if (win && targetAsset && targetAsset.d !== shape.d) {
			push();
			push(`tl.set(shape, { attr: { d: ${j(shape.d)} } }, ${n(win.at)})`);
			push(`  .to(shape, {`);
			push(
				`    morphSVG: { shape: ${j(targetAsset.d)}, type: ${j(s.rotationalMorph ? 'rotational' : 'linear')} },`
			);
			push(`    duration: ${n(win.duration)}, ease: ${j(stop.ease)}, immediateRender: false`);
			push(`  }, ${n(win.at)})`);
			push(`  .fromTo(norm, ${j(shape.norm)},`);
			push(
				`    { ...${j(targetAsset.norm)}, duration: ${n(win.duration)}, ease: ${j(stop.ease)}, immediateRender: false },`
			);
			push(`    ${n(win.at)});`);
			if (JSON.stringify(shape.orient) !== JSON.stringify(targetAsset.orient)) {
				push(`tl.fromTo(orient, ${j(shape.orient)},`);
				push(
					`    { ...${j(targetAsset.orient)}, duration: ${n(win.duration)}, ease: ${j(stop.ease)}, immediateRender: false },`
				);
				push(`    ${n(win.at)});`);
			}
			shape = targetAsset;
		}

		push();
		push(`tl.fromTo(at, { p: ${n(stop.from)} },`);
		push(
			`    { p: ${n(stop.to)}, duration: ${n(stop.travel)}, ease: ${j(stop.ease)}, immediateRender: false }, ${n(stop.travelAt)})`
		);
		push(`  .fromTo(fx, ${j(pickTransform(stop.state))},`);
		push(
			`    { ...${j(pickTransform(target))}, duration: ${n(stop.travel)}, ease: ${j(stop.ease)}, immediateRender: false }, ${n(stop.travelAt)})`
		);
		push(`  .fromTo(shape, ${j(pickPaint(stop.state))},`);
		push(
			`    { ...${j(pickPaint(target))}, duration: ${n(stop.travel)}, ease: ${j(stop.ease)}, immediateRender: false }, ${n(stop.travelAt)});`
		);
		push();
	});

	const cfg = s.life;
	if (cfg?.enabled && (cfg.bob > 0 || cfg.sway > 0 || cfg.pulse > 0)) {
		push(`// ---- idle life: wall-clock secondary motion, independent of the timeline`);
		if (cfg.bob > 0) push(lifeTween('life', 'y', cfg.bob / 2, -cfg.bob / 2, cfg.bobSpeed));
		if (cfg.sway > 0) push(lifeTween('life', 'rotation', -cfg.sway / 2, cfg.sway / 2, cfg.swaySpeed));
		if (cfg.pulse > 0) push(lifeTween('life', 'scale', 1 - cfg.pulse, 1 + cfg.pulse, cfg.pulseSpeed));
		push();
	}

	if (s.trail?.enabled && s.trail.count > 0) {
		const cap = s.trail.count * s.trail.lag + 2;
		push(`// ---- motion trail: each ghost replays an older frame of the lead object`);
		push(`const ghosts = Array.from(root.querySelectorAll('.gasp-ghost')).map(el => {`);
		push(`  const t = gsap.to(el, {`);
		push(`    duration: 1, ease: 'none', paused: true,`);
		push(
			`    motionPath: { path, align: path, alignOrigin: [0.5, 0.5], autoRotate: ${s.autoRotate ? s.rotationOffset || true : false} }`
		);
		push(`  });`);
		push(`  t.progress(0.001); t.progress(0);`);
		push(`  return t;`);
		push(`});`);
		push(`const history = [];`);
		push(`gsap.ticker.add(() => {`);
		push(`  history.unshift(at.p);`);
		push(`  if (history.length > ${cap}) history.length = ${cap};`);
		push(
			`  ghosts.forEach((t, i) => t.progress(history[Math.min(history.length - 1, (i + 1) * ${s.trail.lag})]));`
		);
		push(`});`);
	}

	return lines.join('\n');
}

function lifeTween(el, prop, from, to, speed) {
	return (
		`gsap.fromTo(${el}, { ${prop}: ${n(from)} }, { ${prop}: ${n(to)}, ` +
		`duration: ${n(Math.max(0.1, speed) / 2)}, ease: 'sine.inOut', yoyo: true, repeat: -1 });`
	);
}

function pickTransform(state) {
	return { scale: state.scale, rotation: state.rotate, opacity: state.opacity };
}

function pickPaint(state) {
	return { stroke: state.stroke, strokeWidth: state.strokeWidth, fill: state.fill };
}

/** The markup the generated JS expects to find. */
export function buildMarkup({ layout, track }, { indent = '' } = {}) {
	const s = track.settings;
	const d = buildPathD(track.points, s.closedPath, s.loopTension);
	const ghosts = s.trail?.enabled ? s.trail.count : 0;
	const pad = (depth) => indent + '  '.repeat(depth);

	const rows = [];
	rows.push(
		`${indent}<svg data-gasp viewBox="0 0 ${layout.viewBox.w} ${layout.viewBox.h}" ` +
			`preserveAspectRatio="xMidYMid ${layout.fit}" xmlns="http://www.w3.org/2000/svg">`
	);
	rows.push(`${pad(1)}<path class="gasp-path" d="${d}" fill="none" stroke="none"/>`);

	for (let i = 0; i < ghosts; i++) {
		rows.push(
			`${pad(1)}<g class="gasp-ghost" opacity="${n(s.trail.opacity * (1 - i / (ghosts + 1)))}">` +
				`<use href="#gasp-body"/></g>`
		);
	}

	rows.push(`${pad(1)}<g class="gasp-place">`);
	rows.push(`${pad(2)}<g class="gasp-life">`);
	rows.push(`${pad(3)}<g class="gasp-fx" id="gasp-body">`);
	rows.push(`${pad(4)}<g class="gasp-size">`);
	rows.push(`${pad(5)}<g class="gasp-orient">`);
	rows.push(`${pad(6)}<g class="gasp-norm">`);
	rows.push(
		`${pad(7)}<path class="gasp-shape" d="" fill="none" stroke="#e6edf3" stroke-width="2" ` +
			`stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>`
	);
	rows.push(`${pad(6)}</g>`);
	rows.push(`${pad(5)}</g>`);
	rows.push(`${pad(4)}</g>`);
	rows.push(`${pad(3)}</g>`);
	rows.push(`${pad(2)}</g>`);
	rows.push(`${pad(1)}</g>`);
	rows.push(`${indent}</svg>`);
	return rows.join('\n');
}

/** A standalone page: open it in a browser and the animation just runs. */
export function buildStandaloneHtml(ctx) {
	const markup = buildMarkup(ctx, { indent: '    ' });
	const js = buildTimelineJs(ctx)
		.split('\n')
		.map((l) => (l ? '      ' + l : ''))
		.join('\n');

	return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(ctx.project.name)}</title>
    <style>
      html, body { margin: 0; height: 100%; background: #0d1117; }
      svg[data-gasp] { width: 100%; height: 100%; display: block; }
    </style>
  </head>
  <body>
${markup}

    <script src="${GSAP_CDN}/gsap.min.js"><\/script>
    <script src="${GSAP_CDN}/MotionPathPlugin.min.js"><\/script>
    <script src="${GSAP_CDN}/MorphSVGPlugin.min.js"><\/script>
    <script>
${js}
    <\/script>
  </body>
</html>
`;
}

function escapeHtml(str) {
	return String(str).replace(
		/[&<>"]/g,
		(c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]
	);
}
